name: Dependabot auto-merge

permissions:
  contents: read

on:
  pull_request:

jobs:
  dependabot:
    permissions:
      contents: write
      pull-requests: write
    uses: go-openapi/ci-workflows/.github/workflows/auto-merge.yml@ff87261e2ba4b6a01b2b03bf2738b078e064c8c5 # v0.3.0
    secrets: inherit
