name: Dependabot auto-merge

permissions:
  contents: read

on:
  pull_request:

jobs:
  dependabot:
    permissions:
      contents: write
      pull-requests: write
    uses: go-openapi/ci-workflows/.github/workflows/auto-merge.yml@66b76c435928022c7e44b0dc2346f0fe2197b15b # v0.3.3
    secrets: inherit
