name: Contributors

on:
  schedule:
    - cron: '18 4 * * 6'

  workflow_dispatch:

permissions:
  contents: read

jobs:
  contributors:
    permissions:
      pull-requests: write
      contents: write
    uses: go-openapi/ci-workflows/.github/workflows/contributors.yml@66b76c435928022c7e44b0dc2346f0fe2197b15b # v0.3.3
    secrets: inherit
