name: go test

permissions:
  pull-requests: read
  contents: read

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  test:
    uses: go-openapi/ci-workflows/.github/workflows/go-test.yml@66b76c435928022c7e44b0dc2346f0fe2197b15b # v0.3.3
    secrets: inherit
