name: go test

permissions:
  pull-requests: read
  contents: read

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  test:
    uses: go-openapi/ci-workflows/.github/workflows/go-test.yml@ff87261e2ba4b6a01b2b03bf2738b078e064c8c5 # v0.3.0
    secrets: inherit
