name: Vulnerability scans

on:
  branch_protection_rule:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '18 4 * * 3'

permissions:
  contents: read

jobs:
  scanners:
    permissions:
      contents: read
      security-events: write
    uses: go-openapi/ci-workflows/.github/workflows/scanner.yml@66b76c435928022c7e44b0dc2346f0fe2197b15b # v0.3.3
    secrets: inherit
