name: Release on tag

permissions:
  contents: read

on:
  push:
    tags:
      - v[0-9]+*

jobs:
  gh-release:
    name: Create release
    permissions:
      contents: write
    uses: go-openapi/ci-workflows/.github/workflows/release.yml@ff87261e2ba4b6a01b2b03bf2738b078e064c8c5 # v0.3.0
    with:
      tag: ${{ github.ref_name }}
    secrets: inherit
