name: Release on tag

permissions:
  contents: read

on:
  push:
    tags:
      - v[0-9]+*

jobs:
  gh-release:
    name: Create release
    permissions:
      contents: write
    uses: go-openapi/ci-workflows/.github/workflows/release.yml@66b76c435928022c7e44b0dc2346f0fe2197b15b # v0.3.3
    with:
      tag: ${{ github.ref_name }}
    secrets: inherit
